language: cpp
compiler: gcc
script: make && make test

notifications:
  email:
    recipients:
      - beranekjd1@gcc.edu
    on_success: always # default: change
    on_failure: always # default: always
