language: cpp
compiler: gcc
script: make && make test

before_install:
    - pip install --user cpp-coveralls
    
after_success:
    - coveralls --include "balanced.cpp" --gcov-options '\-lp'

notifications:
  email:
    recipients:
      - beranekjd1@gcc.edu
    on_success: always # default: change
    on_failure: always # default: always
